Quilfoo/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include, re_path
from quilfooapp import views

urlpatterns = [
    path('sp_admin/', admin.site.urls),
    path('admin/',include('adminapp.urls')),
    path('',include('loginapp.urls')),
    path('quilfoo/',include('quilfooapp.urls')),
    path('quilfoo/post/',include('postapp.urls')),
    path('quilfoo/question/',include('questionapp.urls')),
    path('quilfoo/circle/',include('circleapp.urls')),
    path('',views.home,name='beforeLogin'),
    re_path('ckeditor',include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

postapp/models.py
from django.db import models
from loginapp.models import Websiteuser
import uuid
from ckeditor_uploader.fields import RichTextUploadingField
import os
from django import template
register = template.Library()
# Create your models here.

#-------------- Generate unique file name -----------------
def get_file_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join('write/post/', filename)

class UserPost(models.Model):
    postby = models.ForeignKey(Websiteuser,null=True,blank=True,on_delete=models.CASCADE)
    description = RichTextUploadingField(config_name='default',null=True,blank=True)
    report_count = models.PositiveIntegerField(null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True,null=True)
    updated_at = models.DateTimeField(auto_now=True,null=True)
    # id = models.UUIDField(default=uuid.uuid4,unique=True,primary_key=True,editable=False)
    
    
class Postimage(models.Model):
    userpostid = models.ForeignKey(UserPost, on_delete=models.CASCADE)
    image = models.FileField(upload_to=get_file_path,blank=True,null=True,max_length=500)
    file_type = models.SmallIntegerField(null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True,null=True)
    updated_at = models.DateTimeField(auto_now=True,null=True)
    # id = models.UUIDField(default=uuid.uuid4,unique=True,primary_key=True,editable=False)

class UserPostUpvoteDownvote(models.Model):
    userpostid = models.ForeignKey(UserPost,related_name='children',null=True,blank=True,on_delete=models.CASCADE)
    voteby = models.ForeignKey(Websiteuser,null=True,blank=True,on_delete=models.CASCADE)
    Upvote = models.PositiveIntegerField(null=True,blank=True,default=0)
    downvote = models.PositiveIntegerField(null=True,blank=True,default=0)
    created_at = models.DateTimeField(auto_now_add=True,null=True)
    updated_at = models.DateTimeField(auto_now=True,null=True)
    @register.filter
    def in_category(things, Upvote):
        return things.filter(Upvote=Upvote)

class Comment(models.Model):
    userpostid = models.ForeignKey(UserPost, on_delete=models.CASCADE)
    commentwriter = models.ForeignKey(Websiteuser,null=True,blank=True,on_delete=models.CASCADE)
    commentdetail = models.CharField(max_length=1000, null=True,blank=True)
    Upvote = models.PositiveIntegerField(null=True,blank=True)
    downvote = models.PositiveIntegerField(null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True,null=True)
    updated_at = models.DateTimeField(auto_now=True,null=True)
    # id = models.UUIDField(default=uuid.uuid4,unique=True,primary_key=True,editable=False)

class CommentReply(models.Model):
    mainpostid = models.ForeignKey(UserPost, on_delete=models.CASCADE)
    Commentid = models.ForeignKey(Comment,related_name='children', on_delete=models.CASCADE)
    commentreplyuser = models.ForeignKey(Websiteuser, null=True, blank=True, on_delete=models.CASCADE)
    commentdetail = models.CharField(max_length=1000, null=True, blank=True)
    Upvote = models.PositiveIntegerField(null=True, blank=True)
    downvote = models.PositiveIntegerField(null=True, blank=True)
    subreplyof = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE, related_name='sub_replies')
    created_at = models.DateTimeField(auto_now_add=True,null=True)
    updated_at = models.DateTimeField(auto_now=True,null=True)
    # id = models.UUIDField(default=uuid.uuid4,unique=True,primary_key=True,editable=False)

    def __str__(self):
        return f"CommentReply #{self.id}"
    
class Reportpost(models.Model):
    reported_on = models.ForeignKey(UserPost,null=True,blank=True,on_delete=models.CASCADE)
    reported_by = models.ForeignKey(Websiteuser,null=True,blank=True,on_delete=models.CASCADE)
    complaintonpost = models.CharField(max_length=550,null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True,null=True)
    updated_at = models.DateTimeField(auto_now=True,null=True)
    # id = models.UUIDField(default=uuid.uuid4,unique=True,primary_key=True,editable=False)

templates/pages/home/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>post</title>
</head>
<body>
    <a href="{% url 'addPost' %}">Add Post</a><br>
    <a href="{% url 'userProfile' %}">Profile</a><br>
    <a href="{% url 'userLogoutpage' %}">Logout</a><br>
    {% for category in categorys %}
    <p>{{category.topic}}</p>
    <img src="{{ category.image.url }}" alt="" width='20%'>
    {% endfor %}
    {% for user_post_data in user_posts %}
        <div class="profile">
            <img src="{{ user_post_data.user_post.postby.profilepic.url }}" alt="" width="50"style="border-radius: 10px;">
            <span>{{user_post_data.user_post.postby}}</span>
            <button class='follow {{ user_post_data.user_post.postby.id }}' data-catid="{{ user_post_data.user_post.postby.id }}">{% if user_post_data.user_post.postby.id  in follows %}Unfollow {% else %} Follow {% endif %}</button>
        </div>
        <p>{{user_post_data.user_post.description}}</p>
        {% for user_post in user_post_data.user_post.postimage_set.all %}
        <div style="border-bottom: 2px solid;" >
            {% if user_post.file_type == 1 %}
                <Video width="500px" height="200px" controls>
                    <Source src="{{ user_post.image.url }}" type="video/mp4">
                </Video>
            {% else %}
                <img src="{{ user_post.image.url }}" alt="sd">
            {% endif %}        
        {% endfor %}
        <div class="action" style='display: inline-flex;'>
            <button class="likebutton" data-catid="{{ user_post_data.user_post.id }}">Like <span id='upvote{{user_post_data.user_post.id}}'>{{user_post_data.upvote}}</span></button><br>
            <button class="unlikebutton" data-catid="{{ user_post_data.user_post.id }}">Unlike <span id='downvote{{user_post_data.user_post.id}}'>{{user_post_data.downvote}}</span></button><br>
            <a href="{% url 'postComment' user_post_data.user_post.id %}">Comment</a>
        </div>  
    </div>
    {% endfor %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script type="text/javascript">
        $('.likebutton').click(function(){
            var catid;
            catid = $(this).attr("data-catid");
        $.ajax(
        {
            type:"GET",
            url: "like-post/",
            data:{
                     post_id: catid
            },
            success: function( data ) 
            {
                var upvote ='#upvote'+data.id;
                var downvote ='#downvote'+data.id;
                $(upvote).html(data.upvote);
                $(downvote).html(data.downvote);
            }
         })
    });
    $('.unlikebutton').click(function(){
        var catid;
        catid = $(this).attr("data-catid");
    $.ajax(
    {
        type:"GET",
        url: "unlike-post/",
        data:{
                 post_id: catid
        },
        success: function( data ) 
        {
            var upvote ='#upvote'+data.id;
            var downvote ='#downvote'+data.id;
            $(upvote).html(data.upvote);
            $(downvote).html(data.downvote);
    }
     })
    });
    $('.follow').click(function(){
        var catid;
        catid=$(this).attr("data-catid")
        $.ajax(
    {
        type:"GET",
        url: "follow-unfollow/",
        data:{
                 post_id: catid
        },
        success: function( data ) 
        {
            var follow ='.'+data.id;
            $(follow).html(data.follow);
    }
     })   
    });
    </script>
</body>
</html>